### ISSUE TITLE
Double propagation of change event if an-select2 is used

### ISSUE THREAD

**Issue by seeebiii** [K15t/aui-ng#4]
If I use an-select2 as an attribute for an input field so that a select dropdown is generated and add ng-change to the input field, then the change event is fired twice. Combined with ng-model there are two different values propagated.
### Example:

``` html
<input an-select2="myValues()" ng-model="myModel" ng-change="myChangeMethod(myModel)" />
```

myValues() => returns an array of objects where each object has an id and a text attribute

myChangeMethod(myModel) => is called twice; first time myModel contains the value of the option, the second time it's an object with an id and a text attribute

**Comment by xat** [comment]
It seems like this problem happens if select2 is attached to an input and the option `selectData` is set to `true`.
