### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by wtfuii** [K15t/aui-ng#7]
Hello there,

I just wanted to ask if this project is still actively maintained.. I considered to enhance the documentation and maybe even add features..

But if the project is more or less abandoned, i wouldn't invest the effort.

Best regards

**Comment by SvenWalter** [comment]
Hi,
Yes the project is active and we are using the components in production. That's why the project is important for us also in a longer term. Your are very welcome! Please create a pull-request we will review it and take-over the changes. If you have any question, please let us know.

Cheers
Sven

**Comment by wtfuii** [comment]
Hey Sven,

thank you for your quick response, that's something to work with!

Best regards!
